substitutions:
  name: bathroom
  friendly_name: "Bathroom"

esphome:
  name: $name

esp32:
  board: nodemcu-32s
  framework:
      type: arduino
  
# Enable logging
logger:
  # level: VERY_VERBOSE

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

esp32_ble_tracker:

wifi:
  # fast_connect: true 
  reboot_timeout: 0s
  power_save_mode: high
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      manual_ip:
        static_ip: !secret ip_bathroom
        gateway: !secret ip_gateway
        subnet: !secret ip_subnet
    - ssid: !secret wifi_fallback_ssid
      password: !secret wifi_password
      manual_ip:
        static_ip: !secret ip_bathroom
        gateway: !secret ip_gateway
        subnet: !secret ip_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP_${name}"
    password: !secret wifi_password

captive_portal:

sensor:
  - platform: uptime
    internal: false
    update_interval: 60s
    disabled_by_default: True
    id: ${name}_uptime
    name: "${friendly_name} uptime"
      
  - platform: dht
    pin: GPIO32
    model: DHT22
    temperature:
      id: ${name}_temperature
      name: "${friendly_name} Temperature"
      filters:
        lambda: |-
          if(x > 10 && x < 35)
            return x;
          else
            return {};
    humidity:
      id: ${name}_humidity
      name: "${name} Humidity"
    update_interval: 10s

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:A8:64:67"
    bindkey: "eef418daf699a0c188f3bfd17e4565d9"
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    battery_level:
      name: "Living Room Battery Level"

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:22:29:49"
    bindkey: "eef418daf699a0c188f3bfd17e4565d9"
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    battery_level:
      name: "Bedroom Battery Level"

# binary_sensor:
# - platform: gpio
#   pin: GPIO33
#   name: "${friendly_name} Motion"
#   device_class: motion


