substitutions:
  name: box
  friendly_name: "ESP32-S3-Box"
esphome:
  name: box
  friendly_name: Box
esp32:
  board: esp32s3box
  framework:
    type: arduino
external_components:
  # - source: github://nielsnl68/esphome@nvds-t2119-fix2
  #   components: [ touchscreen, tt21100 ]
  #   refresh: 0sec
  - source: github://pr#5997
    components: [ display, touchscreen, tt21100 ]
  # - source: github://pr#4861
  #   components: [ es8311 ]
  # - source: github://rpatel3001/esphome@es7210
  #   components: [ es7210 ]

wifi:
  fast_connect: true
  reboot_timeout: 30s
  power_save_mode: high
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret ip_box
    gateway: !secret ip_gateway
    subnet: !secret ip_subnet
    dns1: !secret ip_gateway

  ap:
    ssid: "ESP_${name}"
    password: !secret wifi_password
ota:
  password: !secret wifi_password
api:
  # encryption:
  #   key: !secret api_encryption_key
  reboot_timeout: 0s
logger:
  # CDC logging is currently not working on the S3
  # See https://github.com/espressif/esp-idf/commit/9924d9f27192a5fab5f66230c72249ecc6cad34c
  #hardware_uart: USB_CDC
  level: VERBOSE
  logs:
  #   esp32_ble: WARN
  #   esp32_ble_tracker: WARN
  #   ble_dist: WARN
  #   sensor: WARN
  #   ledc.output: WARN
  #   component: WARN
  #   ili9xxx: WARN
    tt21100: WARN
    touchscreen: WARN
  #   wifi: WARN
  #   es8311: WARN
  #   i2s_audio: VERBOSE
  #   voice_assistant: VERBOSE
  #   es7210: WARN
        
spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

# qr_code:
#   - id: qr_wifi
#     value: !secret qr_wifi

display:
  - platform: ili9xxx
    model: s3box
    cs_pin: GPIO5
    dc_pin: GPIO4
    reset_pin: GPIO48
    id: lcd

i2c:
  scl: GPIO18
  sda: GPIO8
  scan: true

touchscreen:
  - platform: tt21100
    address: 0x24
    # interrupt_pin: GPIO3
    on_touch:
      - lambda: |-
         ESP_LOGI("cal", "id=%d, x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.id,
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              ); 
    on_release:
      - lambda: |-
          ESP_LOGI("cal", "touches released"
          );
    # Don't use as the reset pin is shared with the display, so the ili9xxx will perform the reset
    #reset_pin: GPIO48
