substitutions:
  name: kaku
  friendly_name: "KlikAanKlikUit"

esphome:
  name: $name
  # includes: 
  #   - modules/kaku.h
  
# esp32:
#   board: nodemcu-32s
#   framework:
#     type: arduino

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: info

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false
  reboot_timeout: 0s
  power_save_mode: high
  manual_ip:
    static_ip: !secret ip_kaku
    gateway: !secret ip_gateway
    subnet: !secret ip_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP_${name}"
    password: !secret wifi_password

# captive_portal:

# remote_receiver:
#   pin: GPIO33
#   dump: 
#     - rc_switch
#   # Settings to optimize recognition of RF devices
#   tolerance: 50%
#   filter: 250us
#   idle: 4ms
#   buffer_size: 2kb

# remote_transmitter:
#   # D1 = GPIO5
#   pin: D1
#   # RF uses a 100% carrier signal
#   carrier_duty_percent: 100%

switch:
  - platform: kaku_old_switch
    id: kaku_D1
    name: kaku D1
    pin: GPIO5
    pulse_length: 375us
    address: D
    unit: 1
  - platform: kaku_old_switch
    id: kaku_D2
    name: kaku D2
    pin: GPIO5
    pulse_length: 375us
    address: D
    unit: 2
  - platform: kaku_old_switch
    id: kaku_D3
    name: kaku D3
    pin: GPIO5
    pulse_length: 375us
    address: D
    unit: 3
    
light:
  - platform: kaku_dimmable_light
    id: kaku_dinner
    name: dinnertable
    pin: GPIO5
    pulse_length: 260us
    address: 1013
    unit: 2
    default_transition_length: 0s